spring.application.name=auth
spring.datasource.url=jdbc:postgresql://localhost:5432/ems
spring.datasource.username=postgres
spring.datasource.password=S0h@9
spring.security.user.name=Sohan
spring.security.user.password=1234   
spring.jpa.hibernate.ddl-auto=update
